services:
  supermicro-license-generator-oci:
    image: docker.io/hlhd/sm-lickitung-gen:v0.0.4
    container_name: supermicro-license-generator-oci
    ports:
      - "8015:8080"   # host:container
    restart: unless-stopped
